#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/tuti
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: dev
